const countries: Record<string, { code: string; name: string; flag: string }> =
  {
    US: { code: "US", name: "United States", flag: "🇺🇸" },
    GB: { code: "GB", name: "United Kingdom", flag: "🇬🇧" },
    CA: { code: "CA", name: "Canada", flag: "🇨🇦" },
    AU: { code: "AU", name: "Australia", flag: "🇦🇺" },
    DE: { code: "DE", name: "Germany", flag: "🇩🇪" },
    FR: { code: "FR", name: "France", flag: "🇫🇷" },
    ES: { code: "ES", name: "Spain", flag: "🇪🇸" },
    IT: { code: "IT", name: "Italy", flag: "🇮🇹" },
    NL: { code: "NL", name: "Netherlands", flag: "🇳🇱" },
    SE: { code: "SE", name: "Sweden", flag: "🇸🇪" },
    NO: { code: "NO", name: "Norway", flag: "🇳🇴" },
    DK: { code: "DK", name: "Denmark", flag: "🇩🇰" },
    FI: { code: "FI", name: "Finland", flag: "🇫🇮" },
    PL: { code: "PL", name: "Poland", flag: "🇵🇱" },
    CH: { code: "CH", name: "Switzerland", flag: "🇨🇭" },
    AT: { code: "AT", name: "Austria", flag: "🇦🇹" },
    BE: { code: "BE", name: "Belgium", flag: "🇧🇪" },
    IE: { code: "IE", name: "Ireland", flag: "🇮🇪" },
    PT: { code: "PT", name: "Portugal", flag: "🇵🇹" },
    GR: { code: "GR", name: "Greece", flag: "🇬🇷" },
    CZ: { code: "CZ", name: "Czech Republic", flag: "🇨🇿" },
    HU: { code: "HU", name: "Hungary", flag: "🇭🇺" },
    RO: { code: "RO", name: "Romania", flag: "🇷🇴" },
    BG: { code: "BG", name: "Bulgaria", flag: "🇧🇬" },
    HR: { code: "HR", name: "Croatia", flag: "🇭🇷" },
    RU: { code: "RU", name: "Russia", flag: "🇷🇺" },
    UA: { code: "UA", name: "Ukraine", flag: "🇺🇦" },
    TR: { code: "TR", name: "Turkey", flag: "🇹🇷" },
    IN: { code: "IN", name: "India", flag: "🇮🇳" },
    CN: { code: "CN", name: "China", flag: "🇨🇳" },
    JP: { code: "JP", name: "Japan", flag: "🇯🇵" },
    KR: { code: "KR", name: "South Korea", flag: "🇰🇷" },
    TW: { code: "TW", name: "Taiwan", flag: "🇹🇼" },
    HK: { code: "HK", name: "Hong Kong", flag: "🇭🇰" },
    SG: { code: "SG", name: "Singapore", flag: "🇸🇬" },
    MY: { code: "MY", name: "Malaysia", flag: "🇲🇾" },
    TH: { code: "TH", name: "Thailand", flag: "🇹🇭" },
    ID: { code: "ID", name: "Indonesia", flag: "🇮🇩" },
    PH: { code: "PH", name: "Philippines", flag: "🇵🇭" },
    VN: { code: "VN", name: "Vietnam", flag: "🇻🇳" },
    PK: { code: "PK", name: "Pakistan", flag: "🇵🇰" },
    BD: { code: "BD", name: "Bangladesh", flag: "🇧🇩" },
    AE: { code: "AE", name: "United Arab Emirates", flag: "🇦🇪" },
    SA: { code: "SA", name: "Saudi Arabia", flag: "🇸🇦" },
    IL: { code: "IL", name: "Israel", flag: "🇮🇱" },
    EG: { code: "EG", name: "Egypt", flag: "🇪🇬" },
    ZA: { code: "ZA", name: "South Africa", flag: "🇿🇦" },
    NG: { code: "NG", name: "Nigeria", flag: "🇳🇬" },
    KE: { code: "KE", name: "Kenya", flag: "🇰🇪" },
    BR: { code: "BR", name: "Brazil", flag: "🇧🇷" },
    MX: { code: "MX", name: "Mexico", flag: "🇲🇽" },
    AR: { code: "AR", name: "Argentina", flag: "🇦🇷" },
    CL: { code: "CL", name: "Chile", flag: "🇨🇱" },
    CO: { code: "CO", name: "Colombia", flag: "🇨🇴" },
    PE: { code: "PE", name: "Peru", flag: "🇵🇪" },
    VE: { code: "VE", name: "Venezuela", flag: "🇻🇪" },
    NZ: { code: "NZ", name: "New Zealand", flag: "🇳🇿" },
    OTHER: { code: "OTHER", name: "Other", flag: "🌍" },
  };

export default countries;
