const SOCKET_RECONNECTION_DELAY = 1000;
const SOCKET_RECONNECTION_DELAY_MAX = 5000;
const SOCKET_RECONNECTION_ATTEMPT_MAX = 5;
const SOCKET_TIMEOUT = 20000;

export {
  SOCKET_RECONNECTION_DELAY,
  SOCKET_RECONNECTION_DELAY_MAX,
  SOCKET_RECONNECTION_ATTEMPT_MAX,
  SOCKET_TIMEOUT,
};
